//
// autogenerated 
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;


namespace project
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Введи список, чурка");
            string subList0 = Convert.ToString(Console.ReadLine());
            string subList1 = Convert.ToString(Console.ReadLine());
            string subList2 = Convert.ToString(Console.ReadLine());
            string subList3 = Convert.ToString(Console.ReadLine());
            string subList4 = Convert.ToString(Console.ReadLine());

            string[] List_6 = new string[5]
            {
                subList0, subList1, subList2, subList3, subList4
            };
            Console.WriteLine("Исходный список ежже баля: ");
            for(int j = 0; j < List_6.Length; j++)
            {
                Console.WriteLine(List_6[j]);
            }

            Console.WriteLine("Отсортированный по длине: ");
            List<string> dictionary = new List<string>() { subList0, subList1, subList2, subList3, subList4 };
            var orderedDic = dictionary.Select(x => new
            {
                val = x,
                length = x.Length
            }).OrderBy(x => x.length).ToList();
            dictionary = orderedDic.Select(x => x.val).ToList();
            Console.WriteLine(string.Join(",", dictionary));
        }
    }   
    
}